HCATALOG-305 hcat shell is not properly picking up the hcat jar
git-svn-id: https://svn.apache.org/repos/asf/incubator/hcatalog/branches/branch-0.4@1300787 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/bin/hcat b/bin/hcat
--- a/bin/hcat
+++ b/bin/hcat
@@ -59,7 +59,11 @@ done
 
 # Find our hcatalog jar
 shopt -s extglob
-HCAT_JAR=$HCAT_PREFIX/share/hcatalog/hcatalog-!(*server-extensions*).jar
+if (( `ls -1 $HCAT_PREFIX/share/hcatalog/hcatalog-[0-9]*.jar | wc -l` > 1 )) ; then
+    echo "Error:  found more than one hcatalog jar in $HCAT_PREFIX/share/hcatalog"
+    exit 1
+fi
+HCAT_JAR=`ls $HCAT_PREFIX/share/hcatalog/hcatalog-[0-9]*.jar`
 
 # Add all of the other jars to our classpath
 for jar in $HCAT_PREFIX/share/hcatalog/lib/*.jar ; do
